menuTranslations:
  main-menu:
    en-US: "Menu"
    pl-PL: "Menu"

  header-main:
    en-US: "Main Quests"
    pl-PL: "Zadania Główne"
    fr-FR: "Quêtes"

  header-side:
    en-US: "Side Quests"
    pl-PL: "Zadania Poboczne"
    fr-FR: "Quêtes"

  header-other:
    en-US: "Other Quests"
    pl-PL: "Zadania Inne"
    fr-FR: "Quêtes"

  header-finished:
    en-US: "Finished Quests"
    pl-PL: "Zadania Ukończone"
    fr-FR: "Quêtes"

  nextP:
    en-US: "Next Page"
    pl-PL: "Kolejna Strona"
    fr-FR: "Page Suivante"

  prevP:
    en-US: "Previous Page"
    pl-PL: "Poprzednia Strona"
    fr-FR: "Page Précédente"

  quest_active:
    en-US: "Active"
    pl-PL: "Aktywne"
    fr-FR: "Active"

  quest_finished:
    en-US: "Finished"
    pl-PL: "Ukończone"
    fr-FR: "Terminé"

  quest_locked:
    en-US: "Locked"
    pl-PL: "Zablokowane"
    fr-FR: "Bloqué"


filters:
  - "seasonal"
  - "event"
  - "exploration"
  - "resource collection"
  - "daily"