menuTranslations:
  main-menu:
    en-US: "Menu"
    pl-PL: "Menu"

  header-main:
    en-US: "Main Quests"
    pl-PL: "Zadania Główne"
    fr-FR: "Quêtes"

  header-side:
    en-US: "Side Quests"
    pl-PL: "Zadania Poboczne"
    fr-FR: "Quêtes"

  header-other:
    en-US: "Other Quests"
    pl-PL: "Zadania Inne"
    fr-FR: "Quêtes"

  header-finished:
    en-US: "Finished Quests"
    pl-PL: "Zadania Ukończone"
    fr-FR: "Quêtes"

  nextP:
    en-US: "Next Page"
    pl-PL: "Kolejna Strona"
    fr-FR: "Page Suivante"

  prevP:
    en-US: "Previous Page"
    pl-PL: "Poprzednia Strona"
    fr-FR: "Page Précédente"

  quest_active:
    en-US: "Active"
    pl-PL: "Aktywne"
    fr-FR: "Active"

  quest_finished:
    en-US: "Finished"
    pl-PL: "Ukończone"
    fr-FR: "Terminé"

  quest_locked:
    en-US: "Locked"
    pl-PL: "Zablokowane"
    fr-FR: "Bloqué"

buttonVisuals:
  backButton:
    text:
      en-US: "Go back"
      pl-PL: "Wróć"
    displayMaterial: red_stained_glass_pane
  previousPageButton:
    text:
      en-US: "Previous page"
      pl-PL: "Poprzednia strona"
    displayMaterial: arrow
  nextPageButton:
    text:
      en-US: "Next page"
      pl-PL: "Następna strona"
    displayMaterial: arrow
  filterButton:
    text:
      en-US: "Filters"
      pl-PL: "Filtry"
    displayMaterial: paper
  mainQuestButton:
    text:
      en-US: "Filters"
      pl-PL: "Filtry"
    displayMaterial: paper
    slot: 19
  sideQuestButton:
    text:
      en-US: "Filters"
      pl-PL: "Filtry"
    displayMaterial: paper
    slot: 21
  otherQuestButton:
    text:
      en-US: "Filters"
      pl-PL: "Filtry"
    displayMaterial: paper
    slot: 23
  finishedQuestButton:
    text:
      en-US: "Filters"
      pl-PL: "Filtry"
    displayMaterial: paper
    slot: 25

filters:
  - "seasonal"
  - "event"
  - "exploration"
  - "resource_collection"
  - "daily"