menuTranslations:
  main-menu:
    en-US: "Menu"
    pl-PL: "Menu"

  header-main:
    en-US: "Main Quests"
    pl-PL: "Zadania Główne"
    fr-FR: "Quêtes"

  header-side:
    en-US: "Side Quests"
    pl-PL: "Zadania Poboczne"
    fr-FR: "Quêtes"

  header-other:
    en-US: "Other Quests"
    pl-PL: "Zadania Inne"
    fr-FR: "Quêtes"

  header-finished:
    en-US: "Finished Quests"
    pl-PL: "Zadania Ukończone"
    fr-FR: "Quêtes"

  nextP:
    en-US: "Next Page"
    pl-PL: "Kolejna Strona"
    fr-FR: "Page Suivante"

  prevP:
    en-US: "Previous Page"
    pl-PL: "Poprzednia Strona"
    fr-FR: "Page Précédente"

  quest_active:
    en-US: "Active"
    pl-PL: "Aktywne"
    fr-FR: "Active"

  quest_finished:
    en-US: "Finished"
    pl-PL: "Ukończone"
    fr-FR: "Terminé"

  quest_locked:
    en-US: "Locked"
    pl-PL: "Zablokowane"
    fr-FR: "Bloqué"

buttonVisuals:
  backButton:
    text:
      en-US: "Go back"
      pl-PL: "Wróć"
    displayMaterial: red_stained_glass_pane
    events:
      - "return"
  previousPage:
    text:
      en-US: "Previous page"
      pl-PL: "Poprzednia strona"
    displayMaterial: arrow
    events:
      - "prevPage"
  nextPage:
    text:
      en-US: "Next page"
      pl-PL: "Następna strona"
    displayMaterial: arrow
    events:
      - "nextPage"

  filters:
    text:
      en-US: "Filters"
      pl-PL: "Filtry"
    displayMaterial: paper
    events:
      - "filter"

  mainQuest:
    text:
      en-US: "Main"
      pl-PL: "Główne"
    displayMaterial: gold_ingot
    events:
      - "openMenu:main"
  sideQuest:
    text:
      en-US: "Side"
      pl-PL: "Poboczne"
    displayMaterial: iron_ingot
    events:
      - "openMenu:side"
  otherQuest:
    text:
      en-US: "Other"
      pl-PL: "Inne"
    displayMaterial: book
    events:
      - "openMenu:quest"
  finishedQuest:
    text:
      en-US: "Finished"
      pl-PL: "Ukończone"
    displayMaterial: writable_book
    events:
      - "openMenu:finished"

  fillerRed:
    text:
      en-US: ""
      pl-PL: ""
    displayMaterial: red_stained_glass_pane

  fillerBlack:
    text:
      en-US: ""
      pl-PL: ""
    displayMaterial: black_stained_glass_pane

filters:
  - "seasonal"
  - "event"
  - "exploration"
  - "resource_collection"
  - "daily"
  - "fighting"

layouts:
  mainMenu:
    layout:
      - "ABABABABA"
      - "         "
      - " C D E F "
      - "         "
      - "         "
      - "ABABABABA"
    buttons:
      A: "fillerRed"
      B: "fillerBlack"
      C: "mainQuest"
      D: "sideQuest"
      E: "otherQuest"
      F: "finishedQuest"

  questMenus:
    layout:
      - "ABABABABA"
      - "         "
      - "         "
      - "         "
      - "         "
      - "ABDBEFCBA"
    buttons:
      A: "fillerRed"
      B: "fillerBlack"
      C: "nextPage"
      D: "previousPage"
      E: "back"
      F: "filters"

settings:
  questStatusVisuals: true
  defaultFillerButton: "fillerRed"