menuTranslations:
  header:
    en-US: "Quests"
    pl-PL: "Zadania"
    fr-FR: "Quêtes"

  nextP:
    en-US: "Next Page"
    pl-PL: "Kolejna Strona"
    fr-FR: "Page Suivante"

  prevP:
    en-US: "Previous Page"
    pl-PL: "Poprzednia Strona"
    fr-FR: "Page Précédente"

  quest_active:
    en-US: "Active"
    pl-PL: "Aktywne"
    fr-FR: "Active"

  quest_finished:
    en-US: "Finished"
    pl-PL: "Ukończone"
    fr-FR: "Terminé"

  quest_locked:
    en-US: "Locked"
    pl-PL: "Zablokowane"
    fr-FR: "Bloqué"